export default {
  name: "Trades",
  component: "Trades",
  settings: "",
  settingsWidth: 300,
  img: "core_components/Trades/Trades.png",
  title: "Trades",
  customTitle: "",
  description: "People trades",
  author: "#core",
  authorLink: "https://github.com/kupi-network/kupi-terminal",
  source: "",
  demo: false,
  // stock: undefined,
  // pair: undefined,
  categories: ["Trades"],
}
