export default {
  name: "ReactStockcharts",
  component: "ReactStockcharts",
  settings: "",
  settingsWidth: 300,
  img: "core_components/Candles/Candles.png",
  title: "Candles",
  customTitle: "",
  description: "Open-High-Low-Close-Value candles chart",
  author: "#core",
  authorLink: "https://github.com/kupi-network/kupi-terminal",
  source: "",
  demo: false,
  timeframe: "30m",
  // stock: undefined,
  // pair: undefined,
  categories: ["Trades", "Candles"],
}
