export default [
  {
    name: "BalanceTable",
    component: "BalanceTable",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalanceTable.png",
    title: "Balance table",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "now",
    stock: "TOTAL",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  },
  {
    name: "BalanceTable",
    component: "BalanceTable",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalanceTable.png",
    title: "Balance table",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "now",
    stock: "",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  },
  {
    name: "BalancePie",
    component: "BalancePie",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalancePie.png",
    title: "Balance pie",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "now",
    stock: "TOTAL",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  },
  {
    name: "BalancePie",
    component: "BalancePie",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalancePie.png",
    title: "Balance pie",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "now",
    stock: "",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  },
  {
    name: "BalanceHistory",
    component: "BalanceHistory",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalanceHistory.png",
    title: "Balance history",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "history",
    stock: "TOTAL",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  },
  {
    name: "BalanceHistory",
    component: "BalanceHistory",
    settings: "",
    settingsWidth: 300,
    img: "core_components/Balance/BalanceHistory.png",
    title: "Balance history",
    customTitle: "",
    description: "",
    author: "#core",
    authorLink: "https://github.com/kupi-network/kupi-terminal",
    source: "",
    demo: true,
    type: "history",
    stock: "",
    channel: "default",
    channels: ["default", "ccxt"],
    categories: ["Private api", "Balance"],
  }
]
